### ISSUE TITLE
Discriminator - activation function

### ISSUE THREAD

**Issue by dav1d-b** [ymirsky/CT-GAN#2]
Hello, I would like to ask why you didn't use any activation function after the last convolutional layer in the discriminator. 

    def build_discriminator(self):
        def d_layer(layer_input, filters, f_size=4, bn=True):
            """Discriminator layer"""
            d = Conv3D(filters, kernel_size=f_size, strides=2, padding='same')(layer_input)
            d = LeakyReLU(alpha=0.2)(d)
            if bn:
                d = BatchNormalization(momentum=0.8)(d)
            return d

        img_A = Input(shape=self.img_shape)
        img_B = Input(shape=self.img_shape)

        # Concatenate image and conditioning image by channels to produce input
        model_input = Concatenate(axis=-1)([img_A, img_B])

        d1 = d_layer(model_input, self.df, bn=False)
        d2 = d_layer(d1, self.df * 2)
        d3 = d_layer(d2, self.df * 4)
        d4 = d_layer(d3, self.df * 8)

        validity = Conv3D(1, kernel_size=4, strides=1, padding='same')(d4)

        return Model([img_A, img_B], validity)

Also the shape of validity is (2,2,2,1) which is not clear to me. Shouldn't it be just one neuron -> real or fake like its depicted in your [publication](https://www.usenix.org/system/files/sec19-mirsky_0.pdf) in figure 6?

**Comment by ymirsky** [comment]
The model is based on a patch-GAN so there is a real/fake label for each region of the image.
